### ISSUE TITLE
Перенести work/analogs на поддомен api

### ISSUE THREAD

**Issue by kenrube** [kenrube/FantLab-API#1]
Роут на получение списка похожих произведений на данный момент: http://fantlab.ru/work{id}/analogs.
Необходимо перенести его на поддомен api и привести к стандартному формату: http://api.fantlab.ru/work/{id}/analogs

**Comment by Mazian** [comment]
https://api.fantlab.ru/work/1/analogs

перенес, но формат выдачи пока не привел к стандарту

**Comment by Mazian** [comment]
Добавлен формат вывода "похожих" в стандарте миникарточек:
https://github.com/FantLab/FantLab-API/blob/master/Docs/work.md#%D0%9F%D0%BE%D1%85%D0%BE%D0%B6%D0%B8%D0%B5-%D0%BF%D1%80%D0%BE%D0%B8%D0%B7%D0%B2%D0%B5%D0%B4%D0%B5%D0%BD%D0%B8%D1%8F
