### ISSUE TITLE
выдача в api оценок юзера

### ISSUE THREAD

**Issue by Mazian** [kenrube/FantLab-API#14]
с параметром w=1,2 отдадутся только оценки юзера для work_id 1 и 2

**Comment by a-pavlov** [comment]
Добрый день, подскажите пожалуйста есть ли уже эндпойнт для выдачи оценок юзера?
Не нашел в документации.

**Comment by kenrube** [comment]
@a-pavlov пока нет. @Mazian вроде уже сделал, но решил не открывать на продакшене до тех пор, пока не разберется с кешированием

**Comment by a-pavlov** [comment]
Спасибо. Подожду тогда от него ответа. Это позволило бы полностью избавиться от селениума и парсинга сайта вот тут https://github.com/a-pavlov/fantlab.

**Comment by kenrube** [comment]
@a-pavlov да, разумеется, полезный функционал

**Comment by a-pavlov** [comment]
@Mazian Подскажите когда планируется вывод в продакшен эндпойнта получения оценок? Очень нужный функционал.

**Comment by Mazian** [comment]
@kenrube немного путает - эта выдача еще не готова. 
Скоро займусь.

**Comment by kenrube** [comment]
@a-pavlov готово: [/Docs/marks.md](https://github.com/kenrube/FantLab-API/blob/master/Docs/marks.md)

**Comment by a-pavlov** [comment]
@kenrube Спасибо, но такое ощущение что работает исключительно ссылка указанная в доке:
https://api.fantlab.ru/user/1/marks?page=2&sort=date&type=novel. Любое изменение параметров или номера юзера приводит к <title>Error 404. Страница не найдена</title>.
P.S. FLUserMarksCollector не будет использоваться, теперь все будет в Qt приложении.

**Comment by kenrube** [comment]
@a-pavlov Это временная проблема на сервере, не связанная с api :)

**Comment by a-pavlov** [comment]
Понятно, подождем. Пока даже на этой странице items массив пустой.

**Comment by a-pavlov** [comment]
Только пока https://api.fantlab.ru/user/1/marks?page=1&sort=date&type=novel возвращает 404.

**Comment by a-pavlov** [comment]
Просто как замечание - если есть фильтр по типу было бы неплохо иметь фильтр по жанру. Или идентификатор жанра в списке оценок раз уж там есть тип произведения. Думаю так потому что для себя строю рекомендации в пределах одного жанра. Можно позже сделать отдельный тикет.

**Comment by kenrube** [comment]
Это уже к @Mazian. Проблема в том, что на сайте на данный момент на странице оценок юзера такого функционала нет, а в выдачу api попадают только требуемые данные (поскольку Вад заодно рефакторит и верстку соответствующих страниц).

**Comment by a-pavlov** [comment]
Хорошо, достаточно ид книги - уже сделал запрос деталей ворка чтобы отсеивать не интересные жанры.

**Comment by Mazian** [comment]
> Хорошо, достаточно ид книги - уже сделал запрос деталей ворка чтобы отсеивать не интересные жанры.

work_id есть в выдаче списка оценок юзера

**Comment by kenrube** [comment]
@Mazian как ни странно, `marks_count` в `user_stat` куда-то потерялся. И в разметке тоже не выводится:
```
Всего оценок: (выведено: 2277)
```

**Comment by kenrube** [comment]
Да нет, нужен. Незачем вычислять то, что в базе хранится одним полем

**Comment by Mazian** [comment]
> @Mazian как ни странно, marks_count в user_stat куда-то потерялся.

Нашелся.
И user_stat убран с остальной статикой в /extended запрос.  
Вывод по умолчанию планирую сократить до оценка/воркид/отзывид

**Comment by kenrube** [comment]
И _response_flag_ можно выпилить за ненужностью

**Comment by Mazian** [comment]
Добавил фильтр по work_id
https://github.com/kenrube/FantLab-API/blob/master/Docs/marks.md#%D0%A1%D0%BE%D0%BA%D1%80%D0%B0%D1%89%D0%B5%D0%BD%D0%BD%D1%8B%D0%B9-%D0%B2%D1%8B%D0%B2%D0%BE%D0%B4-%D0%B8-%D1%84%D0%B8%D0%BB%D1%8C%D1%82%D1%80-%D0%BF%D0%BE-id

Вот теперь закрываем наконец
