### ISSUE TITLE
Починить вывод сущностей в creators в edition

### ISSUE THREAD

**Issue by kenrube** [kenrube/Fantlab-API#19]
При запросе https://api.fantlab.ru/edition/35437 в выводе compiler недостает полей id и type.
При запросе https://api.fantlab.ru/edition/210052 в выводе publishers отсутствуют id и type, вся соответствующая информация свалена в одно поле name.

**Comment by Mazian** [comment]
> При запросе https://api.fantlab.ru/edition/35437 в выводе compiler недостает полей id и type.

но тут некуда ссылаться. этих данных нет.

> При запросе https://api.fantlab.ru/edition/210052 в выводе publishers отсутствуют id и type, вся соответствующая информация свалена в одно поле name.

был не по стандарту написан тэг издательства `[pub=7596:Essentuki]Space Invaders[/pub]`  
[поправил](https://api.fantlab.ru/edition/210052?1)
