### ISSUE TITLE
Перенести work/responses на поддомен api

### ISSUE THREAD

**Issue by kenrube** [kenrube/Fantlab-API#2]
Роут на получение списка отзывов на произведение на данный момент: http://fantlab.ru/work{id}/responses.json.
Необходимо перенести его на поддомен api и привести к стандартному формату: http://api.fantlab.ru/work/{id}/responses.
Здесь же необходимо обработать пагинацию.

**Comment by Mazian** [comment]
сделал
[добавил в доку](https://docs.google.com/document/d/1bFZX0qQNBXwd1PO4H_PVl5W2J9J919yAuYsRZRltBzI/edit#heading=h.hpbyqksmtghq)
