### ISSUE TITLE
Add user's rating to "responses" api

### ISSUE THREAD

**Issue by Aivean** [kenrube/Fantlab-API#20]
Currently both `user/{id}/responses` and `work/{id}/responses` APIs seem to lack user's rating.

To illustrate, here is a review from the site: 
![image](https://user-images.githubusercontent.com/2865203/36067137-1c0a71ae-0e6c-11e8-8381-e59ed8090597.png)
It has rating of "10".

Here is the same review as seen via API: https://api.fantlab.ru/work/1/responses
```json
{
"name": "Hyperion",
"posted_date": "2008-10-02 13:42:43",
"response_id": "87270",
"response_text": "Тот, кто будет читать этот роман как жанровую фантастику, будет разочарован. Будущее, космос, временнЫе парадоксы - это всё тут есть, но если читатель пассивно плывёт по сюжету и не пытается включиться в грандиозный спор, который ...",
"rusname": "Гиперион",
"user_id": "651",
"user_name": "Barros",
"user_sex": "1",
"user_voted": null,
"vote_minus": "0",
"vote_plus": "84",
"work_id": "1",
"work_type_id": "1"
}
```
User's rating is nowhere to be seen.  I have suspicion that the field `"user_voted": null,` is meant to represent user's rating, but currently it's always `null`.

Same thing with [https://api.fantlab.ru/user/651/responses](https://api.fantlab.ru/user/651/responses). User's ratings are not present.

----

Also, a question. Do "response" resources meant to have user votes in addition to reviews? I.e. if user just rates a particular item without writing a text review, will such rating be visible through either `user/{id}/responses` and `work/{id}/responses` APIs?  If not, how such votes can be accessed?

Thanks.

**Comment by kenrube** [comment]
> User's rating is nowhere to be seen. I have suspicion that the field "user_voted": null, is meant to represent user's rating, but currently it's always null.
I think so. It's a bug and should be fixed.

> Also, a question. Do "response" resources meant to have user votes in addition to reviews? I.e. if user just rates a particular item without writing a text review, will such rating be visible through either user/{id}/responses and work/{id}/responses APIs? If not, how such votes can be accessed?
Unfortunately at the moment user's rating to work is unavailable in this case. @Mazian works on user's API (in particular user's marks).

**Comment by kenrube** [comment]
@Mazian Вад, в списках отзывов повсюду отсутствует оценка пользователя произведению, надо вернуть. Есть параметр *user_voted*, но он сейчас всегда *null*.

**Comment by Mazian** [comment]
Hi, Aivean!
Thanks for the detailed issue.

> It has rating of "10".

We added a field `mark` in json. And done structured/renamed other field of this data type.
Docs available in [link](https://github.com/kenrube/Fantlab-API/blob/master/Docs/responses.md) or look [example](https://api.fantlab.ru/work/1/responses)

> a particular item without writing a text review

Yes. In the refactoring process proceeds, this feature will appear in the API
Today such data is only in html - https://fantlab.ru/user1/marks

**Comment by Aivean** [comment]
Awesome!  That was a very fast turnaround.

Thanks, @Mazian and @kenrube! Feel free to close the issue.

**Comment by Mazian** [comment]
Good not busy day. Real rarity! =)
Thx and good luck in your work, @Aivean!
