### ISSUE TITLE
Добавить возможность передавать в метод /user логин в качестве параметра

### ISSUE THREAD

**Issue by kenrube** [kenrube/FantLab-API#21]
На данный момент после авторизации нет возможности узнать id пользователя, чтобы отправить запрос на получение информации о залогинившемся юзере. Возможность передачи логина вместо id должна спасти дело.

**Comment by Mazian** [comment]
/userlogin/{user_login}

**Comment by kenrube** [comment]
Вад, добавь, пожалуйста, в доку и закрой этот issue :)

**Comment by kenrube** [comment]
Правда, вопрос: русские имена endpoint не принимает, как их передавать? Пример: https://api.fantlab.ru/userlogin/неомут

**Comment by Mazian** [comment]
Добавил в доку. поправил и русских имен

https://github.com/kenrube/FantLab-API/blob/master/Docs/user.md#Узнать-id-по-login

**Comment by kenrube** [comment]
Спасибо. Для юзеров с точкой в логине не работает: https://api.fantlab.ru/userlogin/skvortsov.vova
Возможно, и с другими спецсимволами тоже, не проверял

**Comment by Mazian** [comment]
я в страшном сне не представлял что у нас точки разрешены в логине.
тогда это будет совсем по другому сделать нужно...

**Comment by kenrube** [comment]
хах, а Р.Букашка? :))

**Comment by Mazian** [comment]
https://api.fantlab.ru/userlogin?usersearch=Р.Букашка
