### ISSUE TITLE
В api отзывов добавить поля autor_name и user_avatar

### ISSUE THREAD

**Issue by kenrube** [kenrube/FantLab-API#22]

**Comment by Mazian** [comment]
в выдаче свежих отзывов попросить что б отдавало null если запрос страниц выше 20

**Comment by kenrube** [comment]
Если не сложно, добавь еще поле author_id

**Comment by Mazian** [comment]
Авторов может быть больше одного. Поэтому либо тут городить объект авторов полный, как в карточке самого ворка.
Либо - не городить.




Отправлено со стеклышка, натертого спелыми яблоками.

**Comment by Mazian** [comment]
отдает Null
