### ISSUE TITLE
В api отзывов добавить общее количество результатов

### ISSUE THREAD

**Issue by kenrube** [kenrube/FantLab-API#23]
Очень не хватает данных об общем количестве отзывов, хотелось бы вместо просто массива результатов (например, при запросе /user/{id}/responses) получать ответ вроде такого:
```
{
    total_count: Int,    // общее количество отзывов
    items: [                 // список отзывов
        ...
    ]
}
```

**Comment by Mazian** [comment]
https://api.fantlab.ru/work/1/responses
в документации сейчас поменяю данные.

но это было сильное изменение.
если к когото чтото повалится - ты ходи и успокаивай.

**Comment by kenrube** [comment]
Обязательно, Вад :) Спасибо!
