### ISSUE TITLE
Документация по краткому поиску

### ISSUE THREAD

**Issue by kenrube** [kenrube/FantLab-API#27]
Например, https://api.fantlab.ru/search.json?pretty=1&w=1,2,3&e=111,112&a=1,2

**Comment by Mazian** [comment]
это старая выдача краткого поиска. она не будет поддерживаться.
вот новая - https://github.com/kenrube/FantLab-API/blob/master/Docs/search-ids.md

**Comment by kenrube** [comment]
Отлично, тогда закрываю
