### ISSUE TITLE
Перенести недостающую документацию из https://github.com/kenrube/FantLab-client/wiki. Закрыть ее

### ISSUE THREAD

**Issue by kenrube** [kenrube/FantLab-API#32]
- [x] ~регистрация~
- [x] ~восстановление пароля~
- [x] содержимое книжной полки
- [x] создание книжной полки
- [x] удаление книжной полки
- [x] добавление/удаление item с книжной полки
- [x] добавление комментария к item
- [x] отправка сообщения в личке
- [x] подписка на блог
- [x] подписка на статью в блоге
- [x] подписка на тему форума
- [x] выставление оценки произведению
- [x] классификация произведения
- [x] добавление похожего произведения / голосование за имеющееся
- [x] удаление похожего произведения
- [x] добавление/удаление произведение с книжной полки
- [x] ~добавление отзыва~
- [x] плюс/минус отзыва
- [x] ~отправка аннотации~
- [x] ~расширенный поиск произведений~
- [x] ~расширенный поиск изданий~
- [x] ~получение списка рекомендаций~
- [x] удаление рекомендации в мусорку
- [x] добавление/удаление фильма с книжной полки
- [x] плюс/минус поста в форуме
- [x] ~отправка сообщения в форуме~
- [x] ~создание темы/опроса~

**Comment by Mazian** [comment]
Крут, что перенес!
Я дал комент в старом документе.
Закрывай этот тикет ;)

**Comment by kenrube** [comment]
Закрываю
